spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.222.22.199:3306/bori?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy

  jpa :
    hibernate :
      ddl-auto : create
    generate-ddl : false
    properties :
      hibernate :
        format_sql : true

  session:
    store-type: REDIS
  redis:
    host: localhost
    port: 6379
  # JWT Secret Key
  jwt:
    secret: kimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeun